### PR TITLE
✨ More on GBIF dates

### PR DESCRIPTION
**Pull request by FrancisBanville**
I made two new figures showing the distribution of recent GBIF observations (i.e. after 2000) across species. 

I also started using only recent GBIF observations in our validation figures. However, we still need to use only these recent observations when creating GBIF layers (in script 09).  Do you have any idea how to do so @gabrieldansereau?

### CODE REVIEW

**Comment by FrancisBanville** [comment]
I merged your changes and reran all validation analyses using recent GBIF data only. Can you check if everything is good @gabrieldansereau?

**Comment by FrancisBanville** [comment]
Actually, should we use only recent GBIF data in the manuscript @graciellehigino? Or do you want to use them for the response only? @gabrieldansereau and I don't have strong opinions on this.

**Comment by graciellehigino** [comment]
I wondered about this and would lean towards using recent data on the manuscript too, but I'm not sure how to align this with our argument for not cleaning the data. I think it makes sense the same way it makes sense for us to crop the search into our bounding box. So we delimit the data we are using in time and space because it would make ecological sense for most analyses using these data. The same way we don't expect the Serengeti fauna to occur outside the African continent + Eastern Europe, we don't expect many of those populations to occur outside a specific window of time, given the remarkable exploratory history in the African continent. Because it's a validation step, I think it makes sense...? I would vote against filtering if we were using the GBIF data on the main analysis, though.

**Review by graciellehigino — APPROVED** [review]
I'll approve these changes because it's simple to navigate between recent and unfiltered GBIF occurrence data with the code you've written. Thanks for all these improvements, team!

**Comment by FrancisBanville** [comment]
Great, thanks @graciellehigino! I think one little sentence to explain why we used recent GBIF data only is enough.

**Pull request merged**
