### PR TITLE
New_rasters

### LINKED ISSUE #85: Get 50km2 rasters and re-run GBIF analysis
Based on reviewer's comments, we're re-running analyses based on 50km2 rasters to see what changes.

### PR DESCRIPTION
**Pull request by graciellehigino**
closes #85

Got 50km2 rasters and re-run GBIF analysis.

### CODE REVIEW

**Comment by gabrieldansereau** [comment]
Some figures like [figures/beta-div_pred-species.png](figures/beta-div_pred-species.png) are missing the markers for some species. I'll re-run the code to see if I can fix it.

**Comment by gabrieldansereau** [comment]
I'll also fix the color for the removed range on [figures/serval_mismatch_combined.png](figures/serval_mismatch_combined.png)

**Comment by gabrieldansereau** [comment]
What's going on with _Acinonyx jubatus_ losing most of its original IUCN range in [figures/outdegree_predators-orig_range-species.png](figures/outdegree_predators-orig_range-species.png)? There should be some change as for other species, but the drop is really important

**Review by gabrieldansereau — APPROVED** [review]
Code-wise everything is fine for me! I fixed the problems I could see with the missing markers and the removed range that didn't change correctly.

I still don't quite know what's going on with _Acinonyx jubatus_ losing most of its original IUCN range in [figures/outdegree_predators-orig_range-species.png](https://github.com/graciellehigino/ms_range_interactions/pull/figures/outdegree_predators-orig_range-species.png). I suspect it might be related to a change in the IUCN layers themselves.

**Comment by FrancisBanville** [comment]
At first glance, everything seems good to me!

**Comment by FrancisBanville** [comment]
> Code-wise everything is fine for me! I fixed the problems I could see with the missing markers and the removed range that didn't change correctly.
> 
> I still don't quite know what's going on with _Acinonyx jubatus_ losing most of its original IUCN range in [figures/outdegree_predators-orig_range-species.png](https://github.com/graciellehigino/ms_range_interactions/pull/figures/outdegree_predators-orig_range-species.png). I suspect it might be related to a change in the IUCN layers themselves.

If I'm not mistaken, this figure shows the area of the original IUCN range of predators as a function of their number of prey. It's not showing any lost of range. Are you sure you're referring to the right figure @gabrieldansereau?

**Review by FrancisBanville — APPROVED** [review]

**Comment by FrancisBanville** [comment]
> If I'm not mistaken, this figure shows the area of the original IUCN range of predators as a function of their number of prey. It's not showing any loss of range. Are you sure you're referring to the right figure @gabrieldansereau?

After discussing it with @gabrieldansereau almost two months ago, he was actually referring to the right figure. The new IUCN layers seem to have smaller ranges for *Acinonyx jubatus* compared to the layers we previously used. However, I don't think we should worry too much about it since it doesn't impact our analysis or interpretation.

**Comment by FrancisBanville** [comment]
Are we ready to merge this to the master branch @graciellehigino and @gabrieldansereau?

**Comment by gabrieldansereau** [comment]
Fine for me!

**Pull request merged**
